# Generated by Django 3.0.5 on 2020-04-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ini_app', '0005_auto_20200410_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
